import { PortfolioData } from '../types/portfolio';

export const initialPortfolioData: PortfolioData = {
  personal: {
    name: 'Piyush Kumar',
    firstName: 'Piyush',
    lastName: 'Kumar.',
    title: 'Student & AI Developer',
    subtitle: 'Computer Science at VIT Chennai • Currently Sem 3',
    shortDescription: 'Computer Science student (Semester 3, B.Tech CSE Core) at VIT Chennai passionate about programming, artificial intelligence, and building software that solves practical problems.',
    longDescription: 'Currently in Semester 3 pursuing my B.Tech in CSE Core at VIT Chennai. I enjoy writing clean code, solving algorithmic challenges, building web projects, and exploring practical applications of artificial intelligence and machine learning.',
    aboutIntro: "I like building technologies and fitness. Are you ready to join? Then let's come and build something!",
    college: 'Vellore Institute of Technology (VIT), Chennai',
    degree: 'B.Tech — CSE (Computer Science & Engineering) Core',
    semester: 'Semester 3 (2nd Year)',
    city: 'Chennai',
    state: 'Tamil Nadu',
    location: 'Chennai, Tamil Nadu, India',
    professionalAt: [
      'Fullstack Web Architecture',
      'AI & Machine Learning Systems',
      'Modern Frontend & Interactive UI',
      'Scalable APIs & Cloud Deployment',
    ],
    hobbies: [
      'Fitness & Strength Training',
      'Tech Innovation & Open Source',
      'Competitive Programming',
      'Algorithm Design & Problem Solving',
    ],
    availabilityText: 'Available for projects & collaborations',
    isAvailable: true,
    profileImage: '/assets/images/profile.jpg',
    resumeUrl: '', // Real CV URL; if empty, Download CV CTA is hidden cleanly
    email: 'piyush.kumar2025b@vitstudent.ac.in',
  },

  heroButtons: {
    primary: {
      id: 'btn-contact',
      text: 'Contact Me',
      link: '#contact',
      icon: 'arrow-right',
      variant: 'primary',
      enabled: true,
    },
    secondary: {
      id: 'btn-cv',
      text: 'Download CV',
      link: '',
      icon: 'download',
      variant: 'secondary',
      enabled: false, // Activated when resumeUrl is configured
    },
  },

  navigation: [
    { id: 'nav-home', label: 'Home', href: '#home', enabled: true, order: 1 },
    { id: 'nav-about', label: 'About', href: '#about', enabled: true, order: 2 },
    { id: 'nav-skills', label: 'Skills', href: '#skills', enabled: true, order: 3 },
    { id: 'nav-services', label: 'Services', href: '#services', enabled: true, order: 4 },
    { id: 'nav-projects', label: 'Projects', href: '#projects', enabled: true, order: 5 },
    { id: 'nav-contact', label: 'Contact', href: '#contact', enabled: true, order: 6 },
  ],

  socialLinks: [
    {
      id: '1783687728828',
      name: 'GitHub',
      platform: 'github',
      url: 'https://github.com/piyushkumar2025b-arch',
      tooltip: 'GitHub Profile',
      enabled: true,
      order: 1,
      ariaLabel: 'View GitHub profile',
    },
    {
      id: '1783687810073',
      name: 'LinkedIn',
      platform: 'linkedin',
      url: 'https://www.linkedin.com/in/piyush-kumar-74752b3a5/',
      tooltip: 'LinkedIn Profile',
      enabled: true,
      order: 2,
      ariaLabel: 'Connect on LinkedIn',
    },
    {
      id: '1783690795447',
      name: 'Codeforces',
      platform: 'codeforces',
      url: 'https://codeforces.com/profile/piyush_kumar1392',
      tooltip: 'Codeforces Profile',
      enabled: true,
      order: 3,
      ariaLabel: 'View Codeforces profile',
    },
    {
      id: '1783690843267',
      name: 'LeetCode',
      platform: 'leetcode',
      url: 'https://leetcode.com/u/Piyush_kumar_1392/',
      tooltip: 'LeetCode Profile',
      enabled: true,
      order: 4,
      ariaLabel: 'View LeetCode profile',
    },
    {
      id: '1783691174621',
      name: 'Instagram',
      platform: 'instagram',
      url: 'https://www.instagram.com/piyush._._._.kumar?igsh=MWJzNHF2Z2djdnZveA==',
      tooltip: 'Instagram',
      enabled: true,
      order: 5,
      ariaLabel: 'View Instagram profile',
    },
    {
      id: '1783691223466',
      name: 'Email',
      platform: 'gmail',
      url: 'mailto:piyush.kumar2025b@vitstudent.ac.in',
      tooltip: 'Send an Email',
      enabled: true,
      order: 6,
      ariaLabel: 'Send email to piyush.kumar2025b@vitstudent.ac.in',
    },
    {
      id: '1784528681104',
      name: 'Streamlit',
      platform: 'streamlit',
      url: 'https://share.streamlit.io/user/piyushkumar2025b-arch',
      tooltip: 'Streamlit Apps',
      enabled: true,
      order: 7,
      ariaLabel: 'View Streamlit apps',
    },
  ],

  sectionHeaders: {
    skillsTitle: 'Languages & Tools',
    skillsSubtitle: 'Languages and technologies I work with.',
    servicesTitle: 'What I Do',
    servicesSubtitle: 'Areas where I build, collaborate, and contribute.',
    projectsTitle: 'Projects',
    projectsSubtitle: 'Software projects and tools I have built.',
    aboutTitle: 'About Me',
    aboutSubtitle: 'A little about my journey, studies, and what I do outside of coding.',
    experienceTitle: 'Experience',
    experienceSubtitle: 'Internships and engineering experience.',
    educationTitle: 'Education',
    educationSubtitle: 'Academic background and coursework.',
    researchTitle: 'Research',
    researchSubtitle: 'Explorations and publications.',
    achievementsTitle: 'Achievements',
    achievementsSubtitle: 'Competitions and recognitions.',
    contactTitle: "Get in Touch",
    contactSubtitle: "Feel free to reach out for project inquiries, collaborations, or just to say hello.",
  },

  skills: [
    // Languages & Core
    { id: 'sk-python', name: 'Python', icon: 'python', category: 'languages', color: '#3776ab', url: 'https://www.python.org/', enabled: true, order: 1 },
    { id: 'sk-c', name: 'C', icon: 'c', category: 'languages', color: '#00599c', url: 'https://en.cppreference.com/w/c', enabled: true, order: 2 },
    { id: 'sk-cpp', name: 'C++', icon: 'cpp', category: 'languages', color: '#659ad2', url: 'https://isocpp.org/', enabled: true, order: 3 },
    { id: 'sk-html', name: 'HTML', icon: 'html', category: 'languages', color: '#e44d26', url: 'https://developer.mozilla.org/en-US/docs/Web/HTML', enabled: true, order: 4 },
    { id: 'sk-js', name: 'JavaScript', icon: 'js', category: 'languages', color: '#f7df1e', url: 'https://developer.mozilla.org/en-US/docs/Web/JavaScript', enabled: true, order: 5 },
    { id: 'sk-java', name: 'Java', icon: 'java', category: 'languages', color: '#e76f00', url: 'https://dev.java/', enabled: true, order: 6 },
    { id: 'sk-json', name: 'JSON', icon: 'json', category: 'languages', color: '#38bdf8', url: 'https://www.json.org/', enabled: true, order: 7 },
    { id: 'sk-git', name: 'Git', icon: 'git', category: 'tools', color: '#f05032', url: 'https://git-scm.com/', enabled: true, order: 8 },
    { id: 'sk-sql', name: 'SQL', icon: 'sql', category: 'languages', color: '#00758f', url: 'https://en.wikipedia.org/wiki/SQL', enabled: true, order: 9 },

    // Workbenches Explored [TRIED] & AI
    { id: 'sk-google-colab', name: 'Google Colab', icon: 'googlecolab', category: 'workbenches', color: '#F9AB00', url: 'https://colab.research.google.com/', enabled: true, order: 10 },
    { id: 'sk-antigravity', name: 'Antigravity', icon: 'antigravity', category: 'workbenches', color: '#38BDF8', url: 'https://ai.google.dev/', enabled: true, order: 11 },
    { id: 'sk-cursor', name: 'Cursor', icon: 'cursor', category: 'workbenches', color: '#38BDF8', url: 'https://www.cursor.com/', enabled: true, order: 12 },
    { id: 'sk-kiro', name: 'Kiro', icon: 'kiro', category: 'workbenches', color: '#6366F1', url: 'https://kiro.dev/', enabled: true, order: 13 },
    { id: 'sk-google-ai-studio', name: 'Google AI Studio', icon: 'googleaistudio', category: 'ai', color: '#4285F4', url: 'https://aistudio.google.com/', enabled: true, order: 14 },
    { id: 'sk-opencode', name: 'OpenCode', icon: 'opencode', category: 'workbenches', color: '#10B981', url: 'https://github.com/opencode-ai', enabled: true, order: 15 },
    { id: 'sk-claude-code', name: 'Claude Code', icon: 'claudecode', category: 'workbenches', color: '#D97706', url: 'https://docs.anthropic.com/en/docs/agents-and-tools/claude-code', enabled: true, order: 16 },
    { id: 'sk-n8n', name: 'n8n', icon: 'n8n', category: 'tools', color: '#EA4B71', url: 'https://n8n.io/', enabled: true, order: 17 },
    { id: 'sk-hermes-agent', name: 'Hermes Agent', icon: 'hermesagent', category: 'ai', color: '#A78BFA', url: 'https://nousresearch.com/', enabled: true, order: 18 },
    { id: 'sk-codex', name: 'Codex', icon: 'codex', category: 'ai', color: '#10A37F', url: 'https://openai.com/index/openai-codex/', enabled: true, order: 19 },
    { id: 'sk-figma', name: 'Figma', icon: 'figma', category: 'tools', color: '#F24E1E', url: 'https://www.figma.com/', enabled: true, order: 20 },
    { id: 'sk-rocket', name: 'Rocket', icon: 'rocket', category: 'tools', color: '#F43F5E', url: 'https://rocket.rs/', enabled: true, order: 21 },
    { id: 'sk-replit', name: 'Replit', icon: 'replit', category: 'workbenches', color: '#F26207', url: 'https://replit.com/', enabled: true, order: 22 },
    { id: 'sk-vercel', name: 'Vercel', icon: 'vercel', category: 'devops', color: '#ffffff', url: 'https://vercel.com/', enabled: true, order: 23 },
    { id: 'sk-railway', name: 'Railway', icon: 'railway', category: 'devops', color: '#A855F7', url: 'https://railway.app/', enabled: true, order: 24 },
    { id: 'sk-claude', name: 'Claude', icon: 'claude', category: 'ai', color: '#D97706', url: 'https://claude.ai/', enabled: true, order: 25 },
    { id: 'sk-grok', name: 'Grok', icon: 'grok', category: 'ai', color: '#ffffff', url: 'https://x.ai/', enabled: true, order: 26 },
    { id: 'sk-gemini', name: 'Gemini', icon: 'gemini', category: 'ai', color: '#38BDF8', url: 'https://gemini.google.com/', enabled: true, order: 27 },
    { id: 'sk-deepseek', name: 'DeepSeek', icon: 'deepseek', category: 'ai', color: '#0284C7', url: 'https://www.deepseek.com/', enabled: true, order: 28 },
    { id: 'sk-glm', name: 'GLM', icon: 'glm', category: 'ai', color: '#818CF8', url: 'https://zhipuai.cn/', enabled: true, order: 29 },
    { id: 'sk-vscode', name: 'VS Code', icon: 'vscode', category: 'workbenches', color: '#007ACC', url: 'https://code.visualstudio.com/', enabled: true, order: 30 },
    { id: 'sk-trae', name: 'Trae', icon: 'trae', category: 'workbenches', color: '#38BDF8', url: 'https://www.trae.ai/', enabled: true, order: 31 },
    { id: 'sk-cloudflare', name: 'Cloudflare', icon: 'cloudflare', category: 'devops', color: '#F38020', url: 'https://www.cloudflare.com/', enabled: true, order: 32 },
    { id: 'sk-kubernetes', name: 'Kubernetes', icon: 'kubernetes', category: 'devops', color: '#326CE5', url: 'https://kubernetes.io/', enabled: true, order: 33 },
    { id: 'sk-docker', name: 'Docker', icon: 'docker', category: 'devops', color: '#2496ED', url: 'https://www.docker.com/', enabled: true, order: 34 },
    { id: 'sk-obsidian', name: 'Obsidian', icon: 'obsidian', category: 'tools', color: '#8B5CF6', url: 'https://obsidian.md/', enabled: true, order: 35 },
    { id: 'sk-perplexity', name: 'Perplexity', icon: 'perplexity', category: 'ai', color: '#22B8CD', url: 'https://www.perplexity.ai/', enabled: true, order: 36 },
    { id: 'sk-streamlit', name: 'Streamlit', icon: 'streamlit', category: 'workbenches', color: '#FF4B4B', url: 'https://streamlit.io/', enabled: true, order: 37 },
    { id: 'sk-telegram-bot', name: 'Telegram Bot (Own)', icon: 'telegrambot', category: 'tools', color: '#229ED9', url: 'https://core.telegram.org/bots', enabled: true, order: 38 },
    { id: 'sk-chatgpt', name: 'ChatGPT', icon: 'chatgpt', category: 'ai', color: '#10A37F', url: 'https://chatgpt.com/', enabled: true, order: 39 },
  ],

  services: [
    {
      id: 'srv-fullstack',
      title: 'Full-Stack Development',
      description: 'Building responsive web apps and prototypes with clean frontend and backend code.',
      iconType: 'code',
      iconColor: '#38bdf8',
      enabled: true,
      order: 1,
    },
    {
      id: 'srv-ui',
      title: 'AI & Machine Learning',
      description: 'Exploring machine learning concepts, models, and smart automation pipelines.',
      iconType: 'ai',
      iconColor: '#c084fc',
      enabled: true,
      order: 2,
    },
    {
      id: 'srv-backend',
      title: 'Problem Solving & DSA',
      description: 'Practicing algorithmic problem solving and data structures in C++, Python, and Java.',
      iconType: 'database',
      iconColor: '#fb923c',
      enabled: true,
      order: 3,
    },
    {
      id: 'srv-performance',
      title: 'API & Database Design',
      description: 'Designing structured relational databases with SQL and building clean backend endpoints.',
      iconType: 'performance',
      iconColor: '#4ade80',
      enabled: true,
      order: 4,
    },
  ],

  projects: [
    {
      id: 'proj-ai-analytics-workbench',
      name: 'Streamlit AI Analytics & Data Workbench',
      displayTitle: 'Streamlit AI Analytics & Data Workbench',
      title: 'Streamlit AI Analytics & Data Workbench',
      category: 'Machine Learning & Analytics',
      shortDescription: 'Enterprise data exploration and machine learning workbench delivering automated feature engineering, high-throughput model inference, and real-time visualization dashboards.',
      longDescription: 'A modular, high-throughput analytics workbench engineered to streamline machine learning workflows. Featuring automated exploratory data analysis, dataset anomaly detection, and dynamic predictive modeling with real-time Plotly charts and scikit-learn pipelines.',
      coverImage: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&w=1600&q=80',
      technologies: ['Python', 'Streamlit', 'Pandas', 'Scikit-Learn', 'Plotly', 'FastAPI'],
      liveDemoUrl: 'https://share.streamlit.io/user/piyushkumar2025b-arch',
      githubUrl: 'https://github.com/piyushkumar2025b',
      status: 'Completed',
      date: '2025 - Present',
      featured: true,
      enabled: true,
      order: 1,
      highlights: [
        'Zero-downtime containerized cloud deployment with automated rollbacks',
        'High-concurrency event stream processing with deterministic memory footprint',
        'Multi-layer security isolation with encrypted secret management'
      ],
      highlightStats: [
        { label: 'Uptime SLA', value: '99.9%' },
        { label: 'Latency P99', value: '< 100ms' },
        { label: 'Architecture', value: 'Distributed' },
      ],
      telemetryStatus: 'build: success · cluster: production-west · telemetry: healthy',
    },
    {
      id: 'proj-autonomous-telegram-bot',
      name: 'Cloud Automation & Telegram Bot Engine',
      displayTitle: 'Cloud Automation & Telegram Bot Engine',
      title: 'Cloud Automation & Telegram Bot Engine',
      category: 'Cloud Infrastructure & Bot Engineering',
      shortDescription: 'Distributed asynchronous task orchestrator and intelligent Telegram automation bot delivering instant webhook processing, scheduled monitoring, and system telemetry alerts.',
      longDescription: 'A production-ready automation service handling high-volume concurrent event streams. Features asynchronous event loops, secure token authentication, webhook resilience with exponential backoff, and integration with Docker and cloud storage.',
      coverImage: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=1600&q=80',
      technologies: ['Python', 'AsyncIO', 'Telegram Bot API', 'Docker', 'PostgreSQL', 'Redis'],
      githubUrl: 'https://github.com/piyushkumar2025b',
      status: 'Completed',
      date: '2025',
      featured: true,
      enabled: true,
      order: 2,
      highlights: [
        '99.9% uptime with non-blocking event-driven async message dispatching',
        'Automated webhook retry logic with Redis rate-limiting guarantees',
        'Encrypted environment credential isolation and audit logging'
      ],
      highlightStats: [
        { label: 'Uptime SLA', value: '99.9%' },
        { label: 'Concurrency', value: 'AsyncIO Loop' },
        { label: 'Security', value: 'End-to-End' },
      ],
      telemetryStatus: 'build: success · cluster: production-east · telemetry: healthy',
    },
    {
      id: 'proj-high-perf-data-engine',
      name: 'High-Performance Algorithmic Graph Engine',
      displayTitle: 'High-Performance Algorithmic Graph Engine',
      title: 'High-Performance Algorithmic Graph Engine',
      category: 'Systems Engineering & Algorithms',
      shortDescription: 'Low-latency computational suite written in Modern C++ providing cache-friendly graph algorithms, custom memory allocators, and spatial tree partitioning.',
      longDescription: 'An ultra-optimized algorithmic core engineered in C++20. Implements cache-oblivious B-trees, lock-free queues, parallel Dijkstra and A* pathfinding, and memory arena pooling for zero runtime allocation overhead in mission-critical applications.',
      coverImage: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=1600&q=80',
      technologies: ['C++', 'Modern CMake', 'Data Structures', 'Graph Theory', 'Multi-Threading'],
      githubUrl: 'https://github.com/piyushkumar2025b',
      status: 'Completed',
      date: '2024 - 2025',
      featured: true,
      enabled: true,
      order: 3,
      highlights: [
        'Zero-allocation memory arena pool for deterministic microseconds execution',
        'Multi-threaded SIMD parallel graph search across dense vertex matrices',
        'Comprehensive benchmark suite with strict valgrind memory leak verification'
      ],
      highlightStats: [
        { label: 'Memory Overhead', value: 'Zero Alloc' },
        { label: 'Complexity', value: 'O(V log V + E)' },
        { label: 'Language', value: 'Modern C++20' },
      ],
    },
    {
      id: 'proj-spatial-3d-workstation',
      name: 'Spatial 3D Developer Workstation & Audio Studio',
      displayTitle: 'Spatial 3D Developer Workstation & Studio',
      title: 'Spatial 3D Developer Workstation & Studio',
      category: 'Creative Technology & 3D WebGL',
      shortDescription: 'Immersive WebGL 2.0 interactive workstation featuring 360° orbital navigation, multi-stage post-processing shaders, dynamic cat physics, and synthetic cyber audio loops.',
      longDescription: 'A cutting-edge interactive 3D virtual environment built from the ground up in Three.js and React. Incorporates native 2.0 DPR rendering, hardware 4x MSAA anti-aliasing, ACES Filmic tone mapping, behavioral state machine cat physics, and responsive Web Audio sound synthesis.',
      coverImage: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=1600&q=80',
      technologies: ['TypeScript', 'Three.js', 'React', 'Tailwind CSS', 'Vite', 'Web Audio API'],
      liveDemoUrl: '#projects',
      githubUrl: 'https://github.com/piyushkumar2025b',
      status: 'Completed',
      date: '2026',
      featured: true,
      enabled: true,
      order: 4,
      highlights: [
        'Locked 60 FPS WebGL rendering with custom hardware 4x MSAA passes',
        'Dynamic 60-second autonomous behavioral state machine for 3D cat mascot',
        'Architectural studio lighting with 2048x2048 PCF soft contact shadows'
      ],
      highlightStats: [
        { label: 'Frame Rate', value: '60 FPS' },
        { label: 'Anti-Aliasing', value: '4x MSAA' },
        { label: 'Lighting', value: 'ACES Filmic' },
      ],
    },
  ],
  experience: [],
  education: [
    {
      id: 'edu-vit-chennai',
      institution: 'Vellore Institute of Technology (VIT), Chennai',
      degree: 'B.Tech',
      field: 'Computer Science & Engineering (Core)',
      startDate: '2024',
      endDate: '2028',
      grade: 'Currently in Semester 3',
      description: 'Pursuing core computer science curriculum covering data structures, algorithms, object-oriented programming, and intelligent systems.',
      url: 'https://chennai.vit.ac.in/',
      enabled: true,
      order: 1,
    }
  ],
  research: [],
  achievements: [],

  contact: {
    heading: "Get in Touch",
    description: "Feel free to reach out directly via email or the form below for projects, collaborations, or inquiries.",
    email: 'piyush.kumar2025b@vitstudent.ac.in',
    formEnabled: true,
  },

  footer: {
    copyrightText: '© 2026 Piyush Kumar. All rights reserved.',
    statusText: 'Chennai, India',
    showBackToTop: true,
  },

  visualSettings: {
    enable3DEffects: true,
    enableAnimations: true,
    glowIntensity: 'vibrant',
    showProfileVisual: true,
    showSectionAbout: true,
    showSectionExperience: false,
    showSectionEducation: false,
    showSectionResearch: false,
    showSectionAchievements: false,
    showSectionProjects: true,
    showSectionSkills: true,
    showSectionServices: true,
    showSectionContact: true,
  }
};
